#!/usr/bin/env bash
#===================================================================
# netfit — Debian / Ubuntu 专属内核网络与系统基线优化脚本
# 适用: TUIC / VLESS+Reality 落地机、Relay 中转机、Docker 面板机
# 架构: 模块化 drop-in 配置 (.d 目录)，幂等执行 / 可重复运行
#===================================================================

set -uo pipefail

GREEN="\033[32m"
YELLOW="\033[33m"
CYAN="\033[36m"
RED="\033[31m"
RESET="\033[0m"

# 1. 权限与 Debian / Ubuntu 系统校验
[ "$(id -u)" -eq 0 ] || { echo -e "${RED}[错误] 请使用 root 权限运行此脚本！${RESET}" >&2; exit 1; }
if [ ! -r /etc/os-release ] || ! grep -Eq '^ID=(debian|ubuntu)$' /etc/os-release; then
    echo -e "${RED}[错误] netfit 仅支持 Debian 或 Ubuntu 系统！${RESET}" >&2
    exit 1
fi

SYSCTL_FILE="/etc/sysctl.d/99-netfit.conf"
LIMITS_FILE="/etc/security/limits.d/99-netfit.conf"
SYSTEMD_NOFILE="/etc/systemd/system.conf.d/99-netfit-nofile.conf"
JOURNAL_CONF="/etc/systemd/journald.conf.d/99-netfit-journal.conf"
BBR_MOD_FILE="/etc/modules-load.d/netfit-bbr.conf"
HAS_WARN=0

echo -e "${CYAN}>>> [1/4] 正在检测 BBR 支持并根据物理内存计算网络基线...${RESET}"
rm -f "$BBR_MOD_FILE"
modprobe tcp_bbr 2>/dev/null || true
if sysctl -n net.ipv4.tcp_available_congestion_control 2>/dev/null | grep -qw "bbr"; then
    CC_ALGO="bbr"
    echo "tcp_bbr" > "$BBR_MOD_FILE"
else
    CC_ALGO="cubic"
    HAS_WARN=1
    echo -e "${YELLOW}[警告] 当前内核未检测到 BBR 模块，已回退至 cubic！${RESET}"
fi

# 读取 /proc/meminfo 计算内存页数，动态设置 TCP 全局内存压力阈值 (1/16, 1/8, 1/4)
RAM_MB=$(awk '/^MemTotal:/{printf "%d", $2/1024}' /proc/meminfo)
RAM_PAGES=$(awk '/^MemTotal:/{printf "%d", $2/4}' /proc/meminfo)
[ -z "$RAM_MB" ] || [ "$RAM_MB" -le 0 ] && { RAM_MB=1024; RAM_PAGES=262144; }

TCP_MEM_LOW=$(( RAM_PAGES / 16 ))
TCP_MEM_PRESS=$(( RAM_PAGES / 8 ))
TCP_MEM_MAX=$(( RAM_PAGES / 4 ))
[ "$TCP_MEM_LOW" -lt 4096 ] && TCP_MEM_LOW=4096
[ "$TCP_MEM_PRESS" -lt 8192 ] && TCP_MEM_PRESS=8192
[ "$TCP_MEM_MAX" -lt 16384 ] && TCP_MEM_MAX=16384

# 单 socket 最大缓冲上限默认 25MB (26214400)；小于 800MB 的小内存机自动按 RAM/32 收敛
BUF_MAX=26214400
RAM_CAP=$(( RAM_MB * 32768 ))
[ "$RAM_CAP" -lt "$BUF_MAX" ] && BUF_MAX=$RAM_CAP
[ "$BUF_MAX" -lt 4194304 ] && BUF_MAX=4194304

# 清理早期版本可能遗留在 /etc/sysctl.conf 中的同名配置，防止优先级冲突
if [ -f /etc/sysctl.conf ]; then
    sed -i '/net.core.default_qdisc/d;/net.ipv4.tcp_congestion_control/d;/net.core.rmem_max/d;/net.core.wmem_max/d;/net.ipv4.tcp_rmem/d;/net.ipv4.tcp_wmem/d;/net.ipv4.tcp_mem/d;/net.ipv4.tcp_fastopen/d;/net.ipv4.tcp_mtu_probing/d;/net.ipv4.tcp_slow_start_after_idle/d;/net.ipv4.tcp_timestamps/d;/net.ipv4.tcp_sack/d;/net.ipv4.tcp_tw_reuse/d;/net.ipv4.tcp_fin_timeout/d;/net.ipv4.tcp_keepalive_time/d;/net.ipv4.ip_local_port_range/d;/net.core.somaxconn/d;/net.ipv4.tcp_max_syn_backlog/d;/net.core.netdev_max_backlog/d;/net.ipv4.ip_forward/d;/vm.swappiness/d' /etc/sysctl.conf
fi

cat > "$SYSCTL_FILE" << EOF
# ===================================================================
# Generated by netfit (RAM: ${RAM_MB}MB)
# 注意: sysctl 配置文件不支持行尾注释，所有说明均位于参数上方
# ===================================================================

# [1. 拥塞控制与发包调度]
# 使用 FQ (公平队列) 实现精准发包 pacing，配合 BBR 拥塞控制最大化跨国吞吐
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = ${CC_ALGO}

# [2. 全局 Socket 缓冲区上限 (直接决定 TUIC/UDP 与 TCP 的最大窗口天花板)]
# 默认扩容至 25MB (小内存机按 RAM/32 自动收敛)，解决 QUIC/UDP 默认 208KB 极易丢包限速的问题
net.core.rmem_max = ${BUF_MAX}
net.core.wmem_max = ${BUF_MAX}

# [3. TCP 自动调优读写缓冲区范围 (最小值 / 默认初始值 / 最大值)]
# 保留系统安全的默认初始值 (128KB/64KB) 防高并发爆内存，同时允许单条大流动态扩展至 25MB
net.ipv4.tcp_rmem = 4096 131072 ${BUF_MAX}
net.ipv4.tcp_wmem = 4096 65536 ${BUF_MAX}

# [4. TCP 全局内存压力阈值 (单位: 4KB Page，按物理内存 1/16、1/8、1/4 动态计算)]
# 限制全系统所有 TCP 连接占用的总内存上限，防止小内存 VPS 在流量洪峰时触发 OOM 死机
net.ipv4.tcp_mem = ${TCP_MEM_LOW} ${TCP_MEM_PRESS} ${TCP_MEM_MAX}

# [5. 低延迟与防断流特性]
# 双向开启 TCP Fast Open (客户端+服务端)，减少握手延迟
net.ipv4.tcp_fastopen = 3
# 开启 TCP PMTU 黑洞探测，防止跨国隧道/PPPoE 环境下因大包分片被丢弃导致的连接假死
net.ipv4.tcp_mtu_probing = 1
# 关闭 TCP 空闲慢启动，保持长连接 (Reality/网页/游戏) 停顿数秒后再发包时的满速窗口
net.ipv4.tcp_slow_start_after_idle = 0
# 显式开启 TCP 时间戳与选择性确认 (SACK)，确保 BBR 算法测算 RTT 与丢包恢复机制正常工作
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1

# [6. 短连接回收与本地临时端口池隔离]
# 允许安全复用处于 TIME_WAIT 状态的出站连接，应对代理/中转高频建连
net.ipv4.tcp_tw_reuse = 1
# 将 FIN_WAIT_2 状态超时从默认 60s 缩短至 15s，加快断开连接的资源回收
net.ipv4.tcp_fin_timeout = 15
# 将 TCP 死连接探测时间从默认 7200s (2小时) 缩短至 600s (10分钟)，及时清理异常断网残留连接
net.ipv4.tcp_keepalive_time = 600
# 划定出站临时端口池为 10000-65535 (提供 5.5 万端口)，严密保护 <10000 的固定业务端口不冲突
net.ipv4.ip_local_port_range = 10000 65535

# [7. 高并发队列基线]
# 均衡扩容监听端口全连接队列、SYN 半连接握手队列与网卡接收队列至 16384，抗突发且防缓冲膨胀
net.core.somaxconn = 16384
net.ipv4.tcp_max_syn_backlog = 16384
net.core.netdev_max_backlog = 16384

# [8. 内核转发与内存交换策略]
# 开启 IPv4 内核数据包转发，满足 Relay 中转机端口转发与面板机 Docker 网络需求
net.ipv4.ip_forward = 1
# 将 Swap 交换倾向压低至 10，尽量使用物理内存，避免频繁读写磁盘拖慢代理与数据库响应
vm.swappiness = 10
EOF

if ! sysctl --system >/dev/null; then
    HAS_WARN=1
    echo -e "${YELLOW}[警告] sysctl --system 加载过程中存在部分参数告警，请检查上方输出！${RESET}"
fi

echo -e "${CYAN}>>> [2/4] 正在配置 PAM 与 systemd 全局文件句柄默认上限 (65535)...${RESET}"
mkdir -p /etc/security/limits.d /etc/systemd/system.conf.d
sed -i '/nofile 65535/d' /etc/security/limits.conf 2>/dev/null || true
sed -i '/^DefaultLimitNOFILE=/d' /etc/systemd/system.conf 2>/dev/null || true

cat > "$LIMITS_FILE" << 'EOF'
* soft nofile 65535
* hard nofile 65535
root soft nofile 65535
root hard nofile 65535
EOF

cat > "$SYSTEMD_NOFILE" << 'EOF'
[Manager]
DefaultLimitNOFILE=65535
EOF

systemctl daemon-reexec || HAS_WARN=1
ulimit -SHn 65535 2>/dev/null || true

echo -e "${CYAN}>>> [3/4] 正在永久锁定系统日志上限为 1G 并清理超标日志...${RESET}"
mkdir -p /etc/systemd/journald.conf.d
sed -i '/^SystemMaxUse=/d' /etc/systemd/journald.conf 2>/dev/null || true
cat > "$JOURNAL_CONF" << 'EOF'
[Journal]
SystemMaxUse=1G
EOF
systemctl restart systemd-journald || HAS_WARN=1
journalctl --vacuum-size=1G >/dev/null 2>&1 || true

echo -e "${CYAN}>>> [4/4] 正在统一系统时区为 Asia/Shanghai 并设置 IPv4 优先权重 100...${RESET}"
timedatectl set-timezone Asia/Shanghai || HAS_WARN=1
touch /etc/gai.conf
sed -i '/^[[:space:]]*precedence[[:space:]]\+::ffff:0:0\/96/d' /etc/gai.conf
echo "precedence ::ffff:0:0/96  100" >> /etc/gai.conf

# 实际生效验证与安全兜底读取 (修正 awk '{print $3}' 读取第3列权重值)
ACTUAL_CC=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo "unknown")
ACTUAL_QDISC=$(sysctl -n net.core.default_qdisc 2>/dev/null || echo "unknown")
ACTUAL_RMEM=$(sysctl -n net.core.rmem_max 2>/dev/null || echo "0")
ACTUAL_TCP_RMEM=$(sysctl -n net.ipv4.tcp_rmem 2>/dev/null | tr '\t' ' ')
ACTUAL_TCP_WMEM=$(sysctl -n net.ipv4.tcp_wmem 2>/dev/null | tr '\t' ' ')
ACTUAL_PORTS=$(sysctl -n net.ipv4.ip_local_port_range 2>/dev/null | tr '\t' ' ')
ACTUAL_FWD=$(sysctl -n net.ipv4.ip_forward 2>/dev/null || echo "0")
ACTUAL_GAI=$(grep '^[[:space:]]*precedence[[:space:]]\+::ffff:0:0/96' /etc/gai.conf | awk '{print $3}')

if [ "$HAS_WARN" -eq 0 ]; then
    echo -e "\n${GREEN}================== netfit 基线优化实际生效报告 (全部成功) ==================${RESET}"
else
    echo -e "\n${YELLOW}================== netfit 基线优化实际生效报告 (部分告警) ==================${RESET}"
fi
echo "  拥塞控制与队列   : ${ACTUAL_CC} + ${ACTUAL_QDISC}"
echo "  最大缓冲上限值   : $(( ${ACTUAL_RMEM:-0} / 1048576 )) MB (rmem_max=${ACTUAL_RMEM})"
echo "  读写缓冲范围值   : rmem=[${ACTUAL_TCP_RMEM}] | wmem=[${ACTUAL_TCP_WMEM}]"
echo "  全局内存阈值页   : $(sysctl -n net.ipv4.tcp_mem 2>/dev/null | tr '\t' ' ') (Pages)"
echo "  协议栈特性开关   : TFO=$(sysctl -n net.ipv4.tcp_fastopen 2>/dev/null) | MTU探测=$(sysctl -n net.ipv4.tcp_mtu_probing 2>/dev/null) | 禁慢启动=$(sysctl -n net.ipv4.tcp_slow_start_after_idle 2>/dev/null) | TW复用=$(sysctl -n net.ipv4.tcp_tw_reuse 2>/dev/null)"
echo "  本地临时端口池   : ${ACTUAL_PORTS} (保护 <10000 业务端口)"
echo "  高并发队列基线   : somaxconn=$(sysctl -n net.core.somaxconn 2>/dev/null) | syn=$(sysctl -n net.ipv4.tcp_max_syn_backlog 2>/dev/null) | backlog=$(sysctl -n net.core.netdev_max_backlog 2>/dev/null)"
echo "  内核数据包转发   : net.ipv4.ip_forward = ${ACTUAL_FWD}"
echo "  最大文件句柄数   : limits.d 与 systemd 默认上限 65535 (新启动服务生效)"
echo "  系统日志上限值   : SystemMaxUse=1G (当前占用: $(journalctl --disk-usage 2>/dev/null | awk '{print $7}'))"
echo "  出站协议优先级   : IPv4 优先 (权重 ${ACTUAL_GAI:-未生效})"
echo "  当前系统标准时   : $(date '+%Y-%m-%d %H:%M:%S %Z')"
echo -e "${GREEN}============================================================================${RESET}"
